/* DO NOT EDIT THIS FILE - it is machine generated */
#include "/usr/lib/jvm/java-8-oracle/include/jni.h"
#include "../../../../../../../../usr/lib/jvm/java-8-oracle/include/linux/jni_md.h"
/* Header for class sample_Controller */

#ifndef _Included_sample_Controller
#define _Included_sample_Controller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sample_Controller
 * Method:    press
 * Signature: (C)Z
 */
JNIEXPORT jboolean JNICALL Java_sample_Controller_press
  (JNIEnv *, jobject, jchar);

#ifdef __cplusplus
}
#endif
#endif
